# Name for the workflow
name: 'Terraform GitHub Actions'
# The workflow is run on Git Push
on: "push"

jobs:
# Name for the job
  Terraform_Azure_Deploy:
    runs-on: ubuntu-latest
    steps:
# Checkout the repo
    - name: 'Checkout'
      uses: actions/checkout@master

# Run Terraform init
# Name for the Step
    - name: 'Terraform Init'
# Action used
      uses: hashicorp/terraform-github-actions@master
# Options applied
      with:
        tf_actions_version: 0.12.18
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
# Arguements applied, in this the clientsecet is passed from GitHub secrets
        args: '-var="client_secret=${{ secrets.clientSecret }}"'
      env:
# The GitHub token is auto created in the secrets during the build        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Run Terraform validate
    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.18
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
        args: '-var="client_secret=${{ secrets.clientSecret }}"'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Run Terraform plan
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.18
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
        args: '-var="client_secret=${{ secrets.clientSecret }}"'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Run Terraform apply
    - name: 'Terraform Apply'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.18
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
        args: '-var="client_secret=${{ secrets.clientSecret }}"'     
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
